[package]
name = "opencv-app"
version = "0.1.0"
edition = "2021"

[dependencies]
# workspace
opencv-lib = { path = "../opencv-lib" }

anyhow = "1.0"

[lints]
workspace = true

[profile.release]
panic = 'abort'
