.PHONY: build
build:
	cargo build

.PHONY: run
run:
	cargo run --bin opencv-app

.PHONY: run-grayscale
run-grayscale:
	cargo run --bin app-grayscale

.PHONY: run-blurred
run-blurred:
	cargo run --bin app-blurred

