.PHONY: build
build:
	cargo build

.PHONY: run
run:
	cargo run --bin opencv-app

.PHONY: run-grayscale
run-grayscale:
	cargo run --bin app-grayscale

.PHONY: run-blurred
run-blurred:
	cargo run --bin app-blurred

.PHONY: run-blurred2
run-blurred2:
	cargo run --bin app-blurred2

.PHONY: run-binary
run-binary:
	cargo run --bin app-binary

.PHONY: run-edge
run-binary:
	cargo run --bin app-edge

.PHONY: run-hsv
run-hsv:
	cargo run --bin app-hsv

.PHONY: run-histogram
run-hsv:
	cargo run --bin app-histogram

.PHONY: run-resize
run-resize:
	cargo run --bin app-resize

.PHONY: run-rotate
run-rotate:
	cargo run --bin app-rotate
