.PHONY: build
build:
	cargo build

.PHONY: run
run:
	cargo run --bin image-apps

.PHONY: run-wasm
run-wasm:
	cargo run --bin imgapp-wasm

.PHONY: run-wasm2
run-wasm2:
	cargo run --bin imgapp-wasm2

.PHONY: run-grayscale
run-grayscale:
	cargo run --bin imgapp-grayscale

.PHONY: run-mozaic
run-mozaic:
	cargo run --bin imgapp-mozaic

.PHONY: run-mozaic2
run-mozaic2:
	cargo run --bin imgapp-mozaic2

.PHONY: run-glow-effect
run-glow-effect:
	cargo run --bin imgapp-glow-effect

.PHONY: run-cannyedge
run-cannyedge:
	cargo run --bin imgapp-cannyedge

.PHONY: run-cannyedge2
run-cannyedge2:
	cargo run --bin imgapp-cannyedge2

.PHONY: run-gaussianblur
run-gaussianblur:
	cargo run --bin imgapp-gaussianblur

.PHONY: run-thresholding
run-thresholding:
	cargo run --bin imgapp-thresholding

.PHONY: run-histogram
run-histogram:
	cargo run --bin imgapp-histogram

.PHONY: run-meanfilter
run-meanfilter:
	cargo run --bin imgapp-meanfilter

.PHONY: run-linedetection
run-linedetection:
	cargo run --bin imgapp-line-detection
