.PHONY: build
build:
	cargo build

.PHONY: run
run:
	cargo run --bin image-apps

.PHONY: run-grayscale
run-grayscale:
	cargo run --bin imgapp-grayscale

.PHONY: run-cannyedge
run-cannyedge:
	cargo run --bin imgapp-cannyedge

.PHONY: run-gaussianblur
run-gaussianblur:
	cargo run --bin imgapp-gaussianblur

.PHONY: run-thresholding
run-thresholding:
	cargo run --bin imgapp-thresholding
