.PHONY: build
build:
	cargo build

.PHONY: run
run:
	cargo run --bin opencv-apps

.PHONY: run-template
run-template:
	cargo run --bin app-template

.PHONY: run-template2
run-template2:
	cargo run --bin app-template2

.PHONY: run-template3
run-template3:
	cargo run --bin app-template3

.PHONY: run-grayscale
run-grayscale:
	cargo run --bin app-grayscale

.PHONY: run-blurred
run-blurred:
	cargo run --bin app-blurred

.PHONY: run-blurred2
run-blurred2:
	cargo run --bin app-blurred2

.PHONY: run-binary
run-binary:
	cargo run --bin app-binary

.PHONY: run-edge
run-edge:
	cargo run --bin app-edge

.PHONY: run-hsv
run-hsv:
	cargo run --bin app-hsv

.PHONY: run-histogram
run-histogram:
	cargo run --bin app-histogram

.PHONY: run-resize
run-resize:
	cargo run --bin app-resize

.PHONY: run-rotate
run-rotate:
	cargo run --bin app-rotate
