.PHONY: build
build:
	cargo build

.PHONY: run
run:
	cargo run --bin image-detection-apps

.PHONY: run-phash
run-phash:
	cargo run --bin imadetect-phash

.PHONY: run-phash2
run-phash2:
	cargo run --bin imadetect-phash2

.PHONY: run-template-matching
run-template-matching:
	cargo run --bin imadetect-template-matching

.PHONY: run-template-matching2
run-template-matching2:
	cargo run --bin imadetect-template-matching2
